name: Deploy Laravel to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.203.207.71
          username: ubuntu
          key: ${{ secrets.CI_CD_EC2 }}
          script: |
            set -e
            echo "🚀 Deploying Laravel to EC2..."

            cd /var/www/laravel-app

            # Fix git safe directory issue
            git config --global --add safe.directory /var/www/laravel-app

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone https://github.com/TalhaHabib088/ci-cd-deployement.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # Permissions for ubuntu (to run composer & artisan)
            sudo chown -R ubuntu:www-data /var/www/laravel-app
            sudo chmod -R 775 storage bootstrap/cache

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Run Laravel commands
            # php artisan migrate --force
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Final permissions for nginx
            sudo chown -R www-data:www-data /var/www/laravel-app
            sudo chmod -R 775 storage bootstrap/cache

            # Restart services
            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx

            echo "✅ Deployment complete! e"
